### ISSUE TITLE
Unify ZPKdata

### ISSUE THREAD

**Issue by mfalt** [JuliaControl/ControlSystems.jl#12]
_From @mfalt on March 1, 2016 10:2_

`Zpkdata` or similar is implemented twice and incorrect at least once (in transferfunction.jl 58)
`return SisoZpk(roots(sys.num),roots(sys.den),sys.num[1]/sys.den[1])`

_Copied from original issue: mfalt/Control.jl#29_

**Comment by baggepinnen** [comment]
Is this still an issue?

**Comment by mfalt** [comment]
Seems to be fixed
