### ISSUE TITLE
bodeplot - 'latex' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by dlwalter** [JuliaControl/ControlSystems.jl#129]
I'm getting an error when using bodeplot.  The following code causes it:

```
using ControlSystems
s = tf("s")
H = 1/(s+1)
bodeplot(H)
```

I get the following message:

```
'latex' is not recognized as an internal or external command,
operable program or batch file.
'latex' is not recognized as an internal or external command,
operable program or batch file.
latex: failed to create a dvi file
latex: failed to create a dvi file
```

It also creates a tex file in the directory named:
33865466217e273735d668289c47cd88.tex

**Comment by baggepinnen** [comment]
That's interesting.. which backend do you have activated for `Plots.jl`? Try if possible change backend to see if it's backend specific.

**Comment by baggepinnen** [comment]
Do you see the same issue if you call plots yourself?
```julia
using Plots
plot(randn(10))
gr()
plot(randn(10))
```

**Comment by dlwalter** [comment]
Ran you code no problem.  Plot shows up and no messages.  I guess that it
may be because this plots code doesn't run any latex text.

When bodeplot generates those errors I also notice that the bodeplot legend
is blank.

**Comment by dlwalter** [comment]
![capture](https://user-images.githubusercontent.com/6790455/40244914-01f14960-5a79-11e8-8500-169e44e0b992.PNG)

**Comment by zhiyuanryanchen** [comment]
![](https://user-images.githubusercontent.com/6790455/40244914-01f14960-5a79-11e8-8500-169e44e0b992.PNG)

I have a similar problem using Julia 1.4.0

**Comment by baggepinnen** [comment]
The gr backend has suffered from a lot font issues,. You can change backend if you'd like a nicer looking output, I prefer plotly for almost everything nowadays.

**Comment by baggepinnen** [comment]
Does not appear to be a problem anymore :)
