### ISSUE TITLE
I tried to use the dlqr example but I get an error.

### ISSUE THREAD

**Issue by sleepingAgain** [JuliaControl/ControlSystems.jl#132]
h = 0.1
A = [1 h; 0 1]
B = [0;1]
C = [1 0]
sys = ss(A,B,C,0, h)
Q = eye(2)
R = eye(1)
L = dlqr(A,B,Q,R) # lqr(sys,Q,R) can also be used

u(t,x) = -L*x # Form control law,
t=0:h:5
x0 = [1,0]
y, t, x, uout = lsim(sys,u,t,x0)
plot(t,x, lab=["Position", "Velocity"]', xlabel="Time [s]")

I tried to use the above example from the documentation but I get the following error:
DimensionMismatch("Cannot left-divide transposed vector by matrix")
Stacktrace:
 [1] dlqr(::Array{Float64,2}, ::Array{Int64,1}, ::Array{Float64,2}, ::Array{Float64,2}) at C:\...\.julia\v0.6\controlSystems\src\synthesis.jl:90

Please keep in mind that I am not familiar with Julia, just thought to try it out as I am seeking a MATLAB alternative.

**Comment by baggepinnen** [comment]
See branch Julia 0.7 f or a fix of that bug. Should be pulled soon

**Comment by baggepinnen** [comment]
The original error is now resolved. #206 updates the docstring example slightly as well. The new docstring example is
```julia
using LinearAlgebra # For identity matrix I
h = 0.1
A = [1 h; 0 1]
B = [0;1]
C = [1 0]
sys = ss(A,B,C,0, h)
Q = I
R = I
L = dlqr(A,B,Q,R) # lqr(sys,Q,R) can also be used

u(x,t) = -L*x # Form control law,
t=0:h:5
x0 = [1,0]
y, t, x, uout = lsim(sys,u,t,x0=x0)
plot(t,x, lab=["Position"  "Velocity"], xlabel="Time [s]")
```
