### ISSUE TITLE
Implement the lqg function (Linear Quadratic Gaussian) - feature request -

### ISSUE THREAD

**Issue by ufechner7** [JuliaControl/ControlSystems.jl#133]
Hello,
LQG controllers give better results than LQR controllers by using a Kalman filter for state estimation.
An open source implementation can be found here:
https://help.scilab.org/docs/6.0.1/en_US/lqg.html
It would be very nice if this function could be added.
Uwe

**Comment by baggepinnen** [comment]
Just use lqr function with transposed C instead of B and transpose the
result.

**Comment by baggepinnen** [comment]
See function `kalman` and type `LQG`
