### ISSUE TITLE
travis-ci broken

### ISSUE THREAD

**Issue by ufechner7** [JuliaControl/ControlSystems.jl#138]
I think that for all pull requests travis-ci fails:
```
Installing dependency libgtk-3-dev via `apt-get install libgtk-3-dev`:
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
```
This should be fixed.

**Comment by mfalt** [comment]
It seems to be caused when building Gtk.jl and is not our problem, but it is related to our plots-tests. I think we are removing those tests anyway since they are unreliable.

**Comment by mfalt** [comment]
This seems to be fixed? Otherwise feel free to reopen
