### ISSUE TITLE
Create new milestone v0.5 or similar

### ISSUE THREAD

**Issue by ufechner7** [JuliaControl/ControlSystems.jl#154]
After 0.4 is tagged, please create a new milestone and close or move the issues assigned to milestone 0.3 and 0.4 (which are not fixed).

Thanks for the good work! :)

Uwe

**Comment by mfalt** [comment]
The plan is to update the package to julia 0.7/1.0 as soon as possible. That would be v0.5. After that, I think we should do a few changes, such as moving Discrete/Continuous into the type signature and create a type for static systems (to allow for proper type-stable concatenation of systems with numbers). Then I think we should make sure everything is relatively stable and tag 1.0.0. I'll add milestones and create a roadmap.
