### ISSUE TITLE
Support for sybolic values in LTIsystem?

### ISSUE THREAD

**Issue by mfalt** [JuliaControl/ControlSystems.jl#19]
_From @baggepinnen on February 21, 2016 12:30_

It would be nice with support for transfer functions with SymPy symbols 

_Copied from original issue: mfalt/Control.jl#13_

**Comment by baggepinnen** [comment]
We currently do this, but do not have any symbolic features. Such features are probably outside the scope of this package as that would require a new and heavy dependency. I'm currently working on a little add-on package that implements such support, but it will live as a separate package.
