### ISSUE TITLE
Provide help for functions

### ISSUE THREAD

**Issue by mfalt** [JuliaControl/ControlSystems.jl#23]
_From @baggepinnen on February 19, 2016 16:50_

So that one can write
`?func` and get a meaningful help text

We should keep a list here of all the functions that are lacking proper doc-string:

**Comment by ufechner7** [comment]
```
help?> ss
search: @s_str set_zero_subnormals ss ss2tf issym assert isspace issubset issticky

  No documentation found.
```

**Comment by mfalt** [comment]
Thanks, we have added docstrings to these and pretty much all of the functions have some sort of documentation now, although they could be longer and better. I will close this in favor of the other issue on documentation.
