### ISSUE TITLE
Unity feedback of discrete-time system

### ISSUE THREAD

**Issue by olof3** [JuliaControl/ControlSystems.jl#304]
`feedback(ss(0.5, 1, 1, 0, 1), 1)` currently throws "sampletime mismatch"

I guess that this will be resolved after pulling the sampletime PR, so this is just a reminder to check that this is indeed the case.

Here are two simple regression tests to add.
```julia
@test feedback(ss(0.5, 1, 1, 0, 1), 1) == ss(-0.5, 1, 1, 0, 1)
@test feedback(1, ss(0.5, 1, 1, 0, 1)) == ss(-0.5, 1, -1, 1, 1)
```

**Comment by olof3** [comment]
We should support feedback with `UniformScaling`, `1` wouldn't really make sense for MIMO systems. Perhaps still makes sense to support feedback with `Number` for the SISO case?

**Comment by mfalt** [comment]
Did we solve this?

**Comment by olof3** [comment]
Nope. This is still an issue. I also found this problem

```julia
@test [ss(1,1,1,0,1) 1] == ss(1, [1 0], 1, [0 1], 1)
```

We've had all these problems for systems with different sample times etc. Couldn't we just rely on `promote` to a greater extent than `convert`? It seems like this would make it a lot easier to get the sampletime right.
