### ISSUE TITLE
Change framestyle for pole-zero maps

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaControl/ControlSystems.jl#335]
This might be personal preference, but I ALWAYS think that pzmaps look way better with the axis at zero, aka with the argument to plot ```framestyle=:zerolines```. Therefore I would like to propose changing this to the default.

(I have never opened an issue before, so please let me know if this is the wrong forum for such a discussion or if I have otherwise behaved improperly)

**Comment by baggepinnen** [comment]
I've never use that option, but I can imagine it would be a good idea. Feel free to open a PR with the change and maybe a before and after picture so others can chime in as well 😃

**Comment by KronosTheLate** [comment]
https://github.com/JuliaControl/ControlSystems.jl/pull/336
