### ISSUE TITLE
Abstract LTI system types should be parameterized by TimeEvol

### ISSUE THREAD

**Issue by baggepinnen** [JuliaControl/ControlSystems.jl#367]
If they are not, one can not dispatch on, say, `AbstractStateSpace{Continuous}` and have to either
- Dispatch on `StateSpace{Continuous}` and reimplementing for other types
- Check `iscontinuous` inside the method

**Comment by olof3** [comment]
Sounds reasonable. Shouldn't also `LtiSystem` be parameterized by `TimeEvol`? I think that I discussed that with @mfalt and he  had some reason for not doing it or was it just that we should wait for a bit?

**Comment by baggepinnen** [comment]
I think it should (`LTISystem{TE}`), unless a compelling reason not to appears.

**Comment by mfalt** [comment]
I can't see any reason why not right now
