### ISSUE TITLE
lsim with :foh

### ISSUE THREAD

**Issue by mfalt** [JuliaControl/ControlSystems.jl#379]
For a continous system, when the input to `lsim` is not smooth, we automatically select a FOH discretization. The discretization is probably correct (have not verified) and the output `y` looks correct, but the simulated states does not correspond to the original states, which can be confusing and lead to errors. This happend for a case where an observer was designed and simulated, and unknown to the user, the simulation was foh and therefore returned the wrong states,

We are using the `x0map` from the `c2d` function to map the `x0` state, but we are not mapping back the states from the simulation. I am not sure if this is possible exactly (i havent looked at the details of foh) but this seems to work quite well
```julia
Pd, x0map = c2d(P, 0.01, :foh)
y, _, x_foh = lsim(Pd2, u, t)
x = x_foh -u*x0map[:,(end-size(u,2)):end]'
```
Maybe someone with more experience with discrete systems can verify if this is the correct approach? @baggepinnen

**Comment by baggepinnen** [comment]
Default has been changed away from `:foh`
