### ISSUE TITLE
ss2tf does not work for MIMO systems

### ISSUE THREAD

**Issue by baggepinnen** [JuliaControl/ControlSystems.jl#38]
it just returns a siso tf

**Comment by nickquinnell** [comment]
in general you cannot convert a state space model to a transfer function - should it return a matrix of tf's?  Or should it return a tf in the SISO case and a matrix of tf's in all other cases?

**Comment by baggepinnen** [comment]
All transfer functions are MIMO in the toolbox, there is no such thing as a
siso transfer function exposed to the user. So a regular MIMO transfer
function should be returned.

**Comment by baggepinnen** [comment]
Fixed in 	0eb3ea7
