### ISSUE TITLE
Issues with struct_ctrb_obsv and sminreal

### ISSUE THREAD

**Issue by baggepinnen** [JuliaControl/ControlSystems.jl#409]
I find that `struct_ctrb_obsv` has a tendency to return zeros a bit too often, for instance in the following simple example. 
```julia
julia> using ControlSystems.DemoSystems: resonant

julia> sminreal(resonant()*resonant())
StateSpace{Continuous, Float64, Matrix{Float64}}
D = 
 0.0

Continuous-time state-space model
```
The code has not been touched for a very long time and seems to be written by @jcrist 6 years ago, do you have any recollection of what it's supposed to do?

This function is used by `zpkdata(::StateSpace)` which in turn is used in, e.g., `pzmap`.

**Comment by jcrist** [comment]
> do you have any recollection of what it's supposed to do?

None at all, apologies.
