### ISSUE TITLE
separate c2d function for returning x0map

### ISSUE THREAD

**Issue by olof3** [JuliaControl/ControlSystems.jl#412]
I find it annoying and inconsistent that `c2d(G, Ts)`  returns a tuple that includes the x0map if `G isa StateSpace` and only the discretized system otherwise. This is annoying when playing around with systems G of different types.

Personally, I'm also rarely interested in the x0map, so I'll have have to do `c2d(G, Ts)[1]` pretty much always.

Suggestion:
Rename `c2d(sys::StateSpace, Ts::Real, method::Symbol=:zoh)` to `c2d_x0map`
and introduce 
```
c2d(sys::StateSpace, Ts::Real, method::Symbol=:zoh) = c2d_x0map(sys, Ts, method::Symbol=:zoh)[1]
```

I guess one could also use `Val` type arguments if we don't want to introduce a new function, similarly to `cholesky`.

There are other functions where one might want different number of return arguments, for example `impulse` and `hinfnorm`, those cases are a lot less clear how to handle. But this change seems obvious to me. I also think it would be good to change to the same pattern for `hinfnorm` but that we should keep `impulse` as it is. Thoughts, @baggepinnen @mfalt @albheim ?

**Comment by baggepinnen** [comment]
I agree, the inconsistency with `x0map` is annoying and I wouldn't mind getting rid of it.
