### ISSUE TITLE
Get rid of the Matrix type parameter in StateSpace

### ISSUE THREAD

**Issue by olof3** [JuliaControl/ControlSystems.jl#413]
Now that we have `HeteroStateSpace` we could get rid of the Matrix type parameter in `StateSpace` which has been quite painful to deal through promotion etc, while it is too inflexible to actually add much value. I think we have thought about this before, and sort of concluded to go ahead on this? @mfalt @baggepinnen

**Comment by baggepinnen** [comment]
If you are talking about the `Matrix{Int}` in `StateSpace{Continuous, Int64, Matrix{Int64}}` I agree, but I would like to keep the `Int`
