### ISSUE TITLE
Custum labels for bodeplot

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaControl/ControlSystems.jl#415]
I just want to show the current behaviour first of all:
## GR without comma in label-array: 
![image](https://user-images.githubusercontent.com/61620837/102614278-3b10e580-4134-11eb-9217-1d8d4eedc334.png)
## GR with comma in label-array: 
![image](https://user-images.githubusercontent.com/61620837/102614298-4401b700-4134-11eb-9daf-4ddfce3a8fe0.png)

## PlotlyJS without comma in label-array:
![image](https://user-images.githubusercontent.com/61620837/102614190-17e63600-4134-11eb-95fc-0b600dd5018c.png)
## PlotlyJS with comma in label-array:
![image](https://user-images.githubusercontent.com/61620837/102614207-1fa5da80-4134-11eb-900c-0a06369c0b42.png)

None of this is what I want - two labels in the legend, according to the traces, colour coded. Am I doing something wrong? Can this be improved by the plotting recipies?

**Comment by baggepinnen** [comment]
I have solved it on my local fork, just need CI to work before I can start submitting PRs, until then, set every other label to an empty string

**Comment by KronosTheLate** [comment]
> I have solved it on my local fork, just need CI to work before I can start submitting PRs, until then, set every other label to an empty string

Amazing. Thank you so much for the fast reply, the permanent upcoming fix, and the band-aid fix. All much appriciated <3
