### ISSUE TITLE
ctrb not working passing A and B matrices as parameters

### ISSUE THREAD

**Issue by martinamaggio** [JuliaControl/ControlSystems.jl#452]
Reporting a problem with the function `ctrb` (running version 0.9.0 of the ControlSystems package, julia version 1.5.3, on Mac OS Catalina 10.15.7).

When I pass the system as parameter, there is no problem executing the function. When I pass the matrices A and B as parameters I get the following error message

```
julia> ctrb(A,B)
ERROR: MethodError: no method matching ctrb(::Array{Float64,2}, ::Array{Float64,1})
Closest candidates are:
  ctrb(::AbstractArray{T,2} where T, ::AbstractArray{T,2} where T) at
  ~/.julia/packages/ControlSystems/lhpZ5/src/matrix_comps.jl:132
```

Simple code example to reproduce the error:
```
using ControlSystems

A = [0.3 0; 0.1 -5]
B = [0; 1]
C = [1 1]
D = 0

sys_ss = ss(A, B, C, D)
ctrb(sys_ss)
ctrb(A, B)
```

**Comment by mfalt** [comment]
The function requires two matrices (Array{Float64,2}) but you have supplied B as a vector (Array{Float64,1}). The ss conductor is nice to automatically handle that and reshape to a matrix, but apparently not ctrb. We should maybe add that.

**Comment by martinamaggio** [comment]
Aha, I confirm it works with `reshape`. I think it would definitively be more user-friendly to integrate reshaping (especially because one doesn't need to reshape with `obsv`).

**Comment by mfalt** [comment]
> 
> 
> Aha, I confirm it works with `reshape`. I think it would definitively be more user-friendly to integrate reshaping (especially because one doesn't need to reshape with `obsv`).

I don't think we have anything like that implemented for `obsv`, but the difference is that, for example, `C = [1 0]` already is a 1x2 matrix. But, it seems that everyuthing should already work if we allow `B` (or `C` in `obsv`) to be vectors.

However, we should probably not allow `C` to be a vector since they are interpreted as column vectors.
