### ISSUE TITLE
feedback function not working

### ISSUE THREAD

**Issue by phelipe** [JuliaControl/ControlSystems.jl#46]
I try run feedback function but I get "UndefVarError: feedback not defined". Code:

`using ControlSystems`
`S1=tf([1],[0.01,1])`
`feedback(S1)`

Is It  a package error or  my code?

**Comment by mfalt** [comment]
It may be that you are running an old version, try
`Pkg.installed("ControlSystems")`
and make sure you get either the latest release `v"0.1.3"` or the latest master `v"0.1.3+"`.
Run
`Pkg.update()`
to get version `v"0.1.3"` or get the latest commit (`v"0.1.3+"`) by running
`Pkg.checkout("ControlSystems")`

**Comment by phelipe** [comment]
That worked
