### ISSUE TITLE
Improved default frequency vector for frequency plots

### ISSUE THREAD

**Issue by jcrist** [JuliaControl/ControlSystems.jl#5]
The current algorithm detects all features (poles and zeros) of the individual channels, and creates a range covering these, expanded to the nearest decades. This approach is ok, but has a few issues:
1. Resonant peaks can have poor resolution, due to not enough points near the peak. MATLAB accomplishes this by increasing resolution near the peaks.
2. Expanding the range to the nearest decade doesn't always include enough space. If the feature is near the edge, the steady state may be achieved outside the expanded bounds, making for a poor looking plot.
3. The current algorithm uses too many points to achieve some level of resolution. This is related to 1. In areas with no features, we don't need a dense sampling.

**Comment by KronosTheLate** [comment]
I want to connect this issue to https://github.com/JuliaControl/ControlSystems.jl/pull/368, as there seems to be large overlap. I do agree with this issue about a higher resolution being an upgrade
