### ISSUE TITLE
Stable docs not linking correctly?

### ISSUE THREAD

**Issue by albheim** [JuliaControl/ControlSystems.jl#570]
Have not looked into how stable is decided, but it links to 0.5.3 which seems old and should probably be updated. Latest docs seems okay.

**Comment by baggepinnen** [comment]
It gives some warnings
https://github.com/JuliaControl/ControlSystems.jl/runs/4130341409?check_suite_focus=true#step:7:232
But it doesn't say that it fails with the deployment anywhere

**Comment by baggepinnen** [comment]
We appear to be missing this line
https://github.com/baggepinnen/ControlSystemIdentification.jl/blob/ee1f254983e83c3d8d4a936248d81d9697081d4b/.github/workflows/docs.yml#L23

**Comment by albheim** [comment]
But why does the latest docs work if that was the problem? Or at least latest it seems to work to me.

**Comment by baggepinnen** [comment]
yeah I have no idea :/

**Comment by ufechner7** [comment]
This link https://juliacontrol.github.io/ControlSystems.jl/stable is working fine for me and points to 1.5.2 which is correct.

Can this bug be closed?
