### ISSUE TITLE
How to generate frequency-response data?

### ISSUE THREAD

**Issue by ErikQQY** [JuliaControl/ControlSystems.jl#677]
Hello guys! Many thanks for your awesome works! In MATLAB, there is [```frd```](https://www.mathworks.com/help/control/ref/frd.html) to create frequency-response data model. But how to do the same thing in ControlSystems.jl?

**Comment by baggepinnen** [comment]
Hey and thanks :) 
There is no `FRD` object in ControlSystems.jl, see [ControlSystemIdentification.FRD](https://baggepinnen.github.io/ControlSystemIdentification.jl/dev/api/#ControlSystemIdentification.FRD)

**Comment by ErikQQY** [comment]
Wow! Thanks a lot! That solve my problem! BTW, I think it would be nice to have ```bodeplot``` method for ```FRD``` to generate bodeplot, is there any plan for this? @baggepinnen

**Comment by ErikQQY** [comment]
Thank you for your quick response! There are complex numbers in my FRD, so if I directly call plot it would throw errors🥲

**Comment by baggepinnen** [comment]
Have you tried? I'm asking because I know it works ;)

```julia
using ControlSystemIdentification, ControlSystems
w = exp10.(LinRange(-2, 2, 200))
r = freqresp(ssrand(1,1,3), w).parent
frd = FRD(w, r)
plot(frd)
```
![image](https://user-images.githubusercontent.com/3797491/165122105-5c04ab50-6bbd-4b37-bdbf-98acdfb23d81.png)

**Comment by ErikQQY** [comment]
Oops, the old version of ControlSystemIdentification.jl caused the problem.🤣 Anyway, thanks a lot!!

**Comment by ErikQQY** [comment]
@baggepinnen Hi there! The plot method of ```FRD``` only generate  the Magnitude-Frequency plot, so I think it would be great to create both Magnitude-Frequency and Phase-Frequency plot like ```bodeplot``` we already have in ControlSystems.jl for FRD type :)

**Comment by ErikQQY** [comment]
Besides, I think add ```nyquistplot```, ```margin``` and ```nicholsplot``` method for ```FRD``` type would also be great ;)
