### ISSUE TITLE
Discontinuous Root Locus

### ISSUE THREAD

**Issue by agerlach** [JuliaControl/ControlSystems.jl#740]
I expect the issue is originating in the sorting in `getpoles`.

```julia
using Plots, ControlSystems
Nroots = -1.0 .+  [-1.732050807568877im, 1.732050807568877im]
Droots =  [0.0, -4.0, -6.0, -0.7 - 0.7141428428542851im, -0.7 + 0.7141428428542851im]
G = zpk(Nroots, Droots, 1.0)
rlocusplot(G, 200)
```

<img width="709" alt="image" src="https://user-images.githubusercontent.com/599421/188734404-01b06a28-c06e-43a4-8fb7-716b86cd409d.png">

**Comment by baggepinnen** [comment]
Thanks for the example!

Fixed in https://github.com/JuliaControl/ControlSystems.jl/pull/741

![image](https://user-images.githubusercontent.com/3797491/188796573-1341180e-6d76-4f4c-bd25-fb665573dbb2.png)

**Comment by agerlach** [comment]
No problem. Thanks for the quick fix!
