### ISSUE TITLE
rlocusplot() does not plot the roots 

### ISSUE THREAD

**Issue by lucasmsoares96** [JuliaControl/ControlSystems.jl#759]
I'm having trouble plotting the root locus diagram. He doesn't show my roots.   

$$
X(s) = \frac{6s+204}{s^3+10s^2+34s} 
$$

```julia
using ControlSystems
sys2 = tf(
	[6,204],
	[1,10,34,0]
)
rlocusplot(sys2)
```
The Julia code above draws the following graph:

![](https://global.discourse-cdn.com/business5/uploads/julialang/original/3X/9/d/9d8375cb119cc5eb87f030d77f19390c5edceecb.png)

But the scilab equivalent shows a root close to -35.

![](https://global.discourse-cdn.com/business5/uploads/julialang/original/3X/1/a/1a53f02d1c728f569c65a6172078965c4968a62e.png)

How do I show the hidden root?

Link to discourse:
<https://discourse.julialang.org/t/rlocusplot-does-not-plot-the-roots/88547?u=lucasmsoares96>

**Comment by baggepinnen** [comment]
With
- https://github.com/JuliaControl/ControlSystems.jl/pull/760

we get 
![image](https://user-images.githubusercontent.com/3797491/197471981-ad041441-7c8d-4f7d-ae9f-3ed945ff0203.png)
