### ISSUE TITLE
rlocus method

### ISSUE THREAD

**Issue by mzaffalon** [JuliaControl/ControlSystems.jl#764]
The method `rlocus` is currently (v1.5.0) is deprecated and calls `rlocusplot`. Is there a plan to re-introduce `rlocus` that returns the root loci, in the same way as `bode`-`bodeplot` and `nyquist`-`nyquistplot`?
If this is the intention and nobody is doing it, I can take a stab at a PR.

**Comment by baggepinnen** [comment]
There is no such intention, but don't let that discourage you from implementing it in a PR if you would find it useful :)

**Comment by baggepinnen** [comment]
Thanks for your contribution :)
