### ISSUE TITLE
Docstrings for Bode and Nyquist plot functions specify incorrect indexing

### ISSUE THREAD

**Issue by olsoni** [JuliaControl/ControlSystems.jl#797]
Since the change in v1.0, the indexing of frequency response functions (like bode and nyquist) is stated to be (ny, nu, nw). This appears to be working properly given a quick test; however, the docstring produced in the REPL still states the previous indexing order (nw, ny, nu).

**Comment by olsoni** [comment]
My suspicion is that this is not limited to just the bode and nyquist functions, but those were the ones I was able to find at a glance

**Comment by baggepinnen** [comment]
Thanks for the report, it has been fixed :)
