### ISSUE TITLE
`bodeplot`... is the magnitude given in dB?

### ISSUE THREAD

**Issue by B-LIE** [JuliaControl/ControlSystems.jl#839]
I'm used to Bodeplots where the magnitude is given in dB (`20*log10(abs(h(jw)))`). It is not 100% clear to what `bodeplot` does, but I *suspect* the magnitude is *not* given in dB... 

Q: does `bodeplot` give the magnitude dB?

**Comment by baggepinnen** [comment]
The docstring for `bodeplot` indicates how to change the magnitude scale
https://juliacontrol.github.io/ControlSystems.jl/stable/lib/plotting/#ControlSystemsBase.bodeplot
you use
https://juliacontrol.github.io/ControlSystems.jl/stable/lib/plotting/#ControlSystemsBase.setPlotScale-Tuple{AbstractString}
