### ISSUE TITLE
zpk view of `NamedStateSpace` structure

### ISSUE THREAD

**Issue by B-LIE** [JuliaControl/ControlSystems.jl#845]
It is not a function I use a lot, but it seems like the `zpk` view of linear systems in `NamedStateSpace` structure does not work. `tf` does work. 
```julia
test = ss([-1 2 3; 0 -2 3; 0 0 -3],[1;2;3],[1 2 3], [0.0])

tf(test)

tf(named_ss(test))

zpk(test)
```
This works (however, `tf` does not work if all numbers are integers -- e.g., if the D-matrix of `test` is set to `[0]`, `tf` fails.).

The following does *not* work:

```julia
zpk(named_ss(test))
```

**Comment by baggepinnen** [comment]
Thanks for the issue, it's closed by #847 and https://github.com/JuliaControl/ControlSystems.jl/commit/20365704630380bc739f134c0ffa379009999459
