### ISSUE TITLE
`sigmaplot` -- possible to just plot largest and smallest singular values?

### ISSUE THREAD

**Issue by B-LIE** [JuliaControl/ControlSystems.jl#846]
`sigmaplot` seems to plot all singular values of a transfer matrix as function of frequency -- at least by default.

**Question**: Is it possible to plot the maximum and minimum singular values *only*? These are of interest, e.g., in *Loop Transfer Recovery*.

**Comment by baggepinnen** [comment]
I implemented this in #848

**Comment by baggepinnen** [comment]
A side note, are you aware of the [`LQGProblem` type in RobustAndOptimalControl](https://juliacontrol.github.io/RobustAndOptimalControl.jl/dev/api/#RobustAndOptimalControl.LQGProblem)? It has some built in LTR support as well as some other convenience interfaces
