### ISSUE TITLE
change to ControlSystems dosent work for import pkg

### ISSUE THREAD

**Issue by juanodecc** [JuliaControl/ControlSystems.jl#877]
I must to edit ControlSystemsBase to use this example

ArgumentError: Package ControlSystemsBase not found in current path.
- Run `import Pkg; Pkg.add("ControlSystemsBase")` to install the ControlSystemsBase package.

https://github.com/JuliaControl/ControlSystems.jl/blob/bfe5e73e9513af2053fdd6c5a9426761b0fee81c/docs/src/examples/analysis.md?plain=1#L8C7-L8C25

**Comment by baggepinnen** [comment]
I'm not sure I understand you, what edit do you have to do?

**Comment by juanodecc** [comment]
ok, I think understand, I just have install ControlSystems package and exist other lighter package with other name. tank you
