### ISSUE TITLE
Documentation/terminology: isn't sampled-data more appropriate than hybrid? 

### ISSUE THREAD

**Issue by hurak** [JuliaControl/ControlSystems.jl#904]
With all humbleness I would like to raise the following terminological issue: when both continuous-time and discrete-time signals are present within a system, such system is called hybrid in this package. For example, as in this [Analysis of hybrid continuous-discrete systems](https://juliacontrol.github.io/ControlSystems.jl/dev/examples/zoh/#Analysis-of-hybrid-continuous-discrete-systems). 

I find the use of the adjective "hybrid" rather unfortunate here. Although there is no absolute standard for the terminology, the common usage these days is, that hybrid systems mean something different (hybrid automata, physical and logical, ....). In fact, having some functionality for hybrid (control) systems in this package would be great too (currently there is some support in [HybridSystems.jl](https://github.com/blegat/HybridSystems.jl), currently mainly motivated by [ReachabilityAnalysis.jl](https://github.com/JuliaReach/ReachabilityAnalysis.jl). 

What would be the alternative adjective here? The "old-school" texts used "sampled-data systems". Citing from the very first page of Astrom, Karl Johan, and Bjorn Wittenmark. Computer-Controlled Systems: Theory and Design. 3rd ed. Upper Saddle River, NJ: Prentice Hall, 1997:
> The computer-controlled system contains both continuous-time signals and sampled, or discrete-time. signals. Such systems have traditionally been called sampled-data systems, and this term will be used here as a synonym for computer-controlled systems.

Maybe it is not perfect, but it is quite settled already. See Chen, Tongwen, and Bruce A. Francis. Optimal Sampled-Data Control Systems. Communications and Control Engineering. London ; New York: Springer, 1996 [[downloadable on the author's web page](https://www.control.utoronto.ca/people/profs/francis/sd_book.pdf)], for another example.

Why not adhering to it? It might help avoid confusion and leave space for possible future implementation of some hybrid control features in the package.

**Comment by baggepinnen** [comment]
> isn't sampled-data more appropriate than hybrid

Perhaps, a sampled-data system is a special case of a hybrid system. I made the change you proposed to the titles in the tutorial
