### ISSUE TITLE
Change input/output plot order of SimResult

### ISSUE THREAD

**Issue by scls19fr** [JuliaControl/ControlSystems.jl#919]
Hello,

I think it will be more "logical" to first plot input and after output by default when both `plotu` and `ploty` are true

![image](https://github.com/JuliaControl/ControlSystems.jl/assets/109167/11be1531-de3b-4995-a545-358b464ec5f1)

Code to reproduce:
```julia
using ControlSystems
using Plots
τ = 2.0  # s (time constant)
K = 1
s = tf("s")
T1 = K / (1 + τ * s)
t = 0:0.01:10
t0 = 1.0
u = 2.0 * (t .>= t0)'
res = lsim(T1, u, t)
plot(res, label=["output" "input"], plotu=true, ploty=true)
```

Called code
https://github.com/JuliaControl/ControlSystems.jl/blob/0d825400f1fd0126a4ccaa63408ba2b38351d47a/lib/ControlSystemsBase/src/plotting.jl#L105

Kind regards

**Comment by scls19fr** [comment]
I also wonder if `lsim` couldn't accept `u` as `Vector{Float}` for single input system like that

Something like

    u = 2.0 * (t . >= t0)

may be enough

**Comment by baggepinnen** [comment]
The default is to not plot the input, so if the user requests this, it makes sense to add this plot after the existing one. Also, this is really a trivial thing and I see no point in changing this behavior and confuse existing users.

If you prefer a different order. you can easily override the default using
```julia
plot(step(P, 10), plotu=true, sp=[2 1])
```
