### ISSUE TITLE
Wiki: Modia?

### ISSUE THREAD

**Issue by ma-laforge** [JuliaControl/ControlSystems.jl#93]
Hi,

I have been reading your wiki on "Restructuring ControlSystems".

You mention the:
> Modia implementation of the Modelica language

This sounds very interesting.  Could you elaborate?  I could only find module "Sims.jl".  Is Modia going to be Tom Short's next iteration?  I do not know where to find information on this.

**Comment by baggepinnen** [comment]
Information about this is still limited,  a brief statement from Hilding
Elmqvist, the founder of Modelica and Modia,  can be found here.

Modia - a new experimental modeling language
https://www.linkedin.com/pulse/modia-new-experimental-modeling-language-hilding-elmqvist
