### ISSUE TITLE
Problem with graphics

### ISSUE THREAD

**Issue by cjruiz** [JuliaControl/ControlSystems.jl#97]
Hello,
I have a non-sense problem. When i use Step, or somtehing like that, i never get a graphic.
For example: 
`using ControlSystems
g = tf(1,1)
step (g)
`

The output is: ([1.0; 1.0; . ; 1.0; 1.0],
0.0:1.0:100.0,)

I cant figure whats going on. Any idea?

**Comment by baggepinnen** [comment]
Hello,

Try the function `stepplot` instead. All Plots are produced by functions
that end with - plot, as bodeplot or nicholsplot.

For this to work you need the packages Plots.jl and a suitable backend,
such as Pyplot or GR.jl

**Comment by cjruiz** [comment]
Hi,
first of all, thanks for the answer.

Unfortnately, it didn't work. Now i have a new error: 
Key error: key "set_facecolor" not found

I have Plots.jl and PyPlot.jl- Actually, it was working a few hours ago, but now i get nothing, and i can't understand. I have no problems plotting arrays, only with ControlSystems. 

Sorry and thanks again.

**Comment by mfalt** [comment]
It is hard to debug this without a stack-trace, could you post the full error you are getting? Which version of julia are you running? Have you updated Plots.jl and PyPlot.jl?

**Comment by cjruiz** [comment]
Julia version -> 0.5.0

Yes, i updated:
Plots version ->0.11.2
PyPlot version ->2.3.2

**Comment by cjruiz** [comment]
Well, is working now. I don't know why, but now it works. After the number 10000 call to bodeplot() Julia started to recompiling and stalling new packages.
![working](https://cloud.githubusercontent.com/assets/28735195/26128816/05090252-3a8e-11e7-8ce5-b0a167b49a54.JPG)
